export let datasOne = {
  associations: [],
  transForm: [],
  columns: [
    {
      date: false,
      displayed: 1,
      col_index: 39,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "title",
      multipleComponentFlag: false,
      index: 0,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "title",
      col_datatype: 0,
      import_flag: false,
      datatype: 0,
      inChart: true,
    },
    {
      date: false,
      displayed: 1,
      col_index: 1,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "data_id",
      multipleComponentFlag: false,
      primary_key_flag: 1,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "data_id",
      col_datatype: 0,
      col_desc: "主键ID",
      import_flag: false,
      col_alias: "主键ID",
      queryable: 1,
      datatype: 0,
      alias: "主键ID",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 2,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "parent_id",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "parent_id",
      col_datatype: 0,
      col_desc: "外键ID",
      import_flag: false,
      col_alias: "外键ID",
      datatype: 0,
      alias: "外键ID",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 3,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "office_id",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "office_id",
      col_datatype: 0,
      col_desc: "组织ID",
      import_flag: false,
      col_alias: "组织ID",
      datatype: 0,
      alias: "组织ID",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 4,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "create_member",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "create_member",
      col_datatype: 0,
      col_desc: "创建人",
      import_flag: false,
      col_alias: "创建人",
      datatype: 0,
      alias: "创建人",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 6,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "create_member_ip_address",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "create_member_ip_address",
      col_datatype: 0,
      col_desc: "创建人IP地址",
      import_flag: false,
      col_alias: "创建人IP地址",
      datatype: 0,
      alias: "创建人IP地址",
      inChart: false,
    },
    {
      date: true,
      displayed: 1,
      col_index: 5,
      timeGranularity: 7,
      not_null_flag: 0,
      column: "create_time",
      multipleComponentFlag: false,
      index: 1,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "create_time",
      col_datatype: 6,
      col_desc: "创建时间",
      import_flag: false,
      col_alias: "创建时间",
      datatype: 6,
      alias: "创建时间",
      inChart: false,
      order: 1,
    },
    {
      date: false,
      displayed: 1,
      col_index: 7,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "last_modifier",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "last_modifier",
      col_datatype: 0,
      col_desc: "修改人",
      import_flag: false,
      col_alias: "修改人",
      datatype: 0,
      alias: "修改人",
      inChart: false,
    },
    {
      date: true,
      displayed: 1,
      col_index: 8,
      timeGranularity: 7,
      not_null_flag: 0,
      column: "last_modify_time",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "last_modify_time",
      col_datatype: 6,
      col_desc: "修改时间",
      import_flag: false,
      col_alias: "修改时间",
      datatype: 6,
      alias: "修改时间",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 9,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "last_modifier_ip_address",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "last_modifier_ip_address",
      col_datatype: 0,
      col_desc: "修改人IP地址",
      import_flag: false,
      col_alias: "修改人IP地址",
      datatype: 0,
      alias: "修改人IP地址",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 10,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "flow_instance_id",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "flow_instance_id",
      col_datatype: 0,
      col_desc: "流程实例id",
      import_flag: false,
      col_alias: "流程实例id",
      datatype: 0,
      alias: "流程实例id",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 11,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "flow_name",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "flow_name",
      col_datatype: 0,
      col_desc: "流程名称",
      import_flag: false,
      col_alias: "流程名称",
      datatype: 0,
      alias: "流程名称",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 12,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "flow_instance_name",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "flow_instance_name",
      col_datatype: 0,
      col_desc: "流程实例名称",
      import_flag: false,
      col_alias: "流程实例名称",
      datatype: 0,
      alias: "流程实例名称",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 13,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "handle_usernames",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "handle_usernames",
      col_datatype: 0,
      col_desc: "处理人",
      import_flag: false,
      col_alias: "处理人",
      datatype: 0,
      alias: "处理人",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 15,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "process_status",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "process_status",
      col_datatype: 0,
      col_desc: "流程状态",
      import_flag: false,
      col_alias: "流程状态",
      datatype: 0,
      alias: "流程状态",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 14,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "business_status",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "business_status",
      col_datatype: 0,
      col_desc: "业务状态",
      import_flag: false,
      col_alias: "业务状态",
      datatype: 0,
      alias: "业务状态",
      ruleConditions: [
        {
          unit: 0,
          datatype: 0,
          column: "business_status",
          alias: "业务状态",
          compareObj: "待发起",
          satisfy_type: 0,
          varibleType: "values",
          type: 5,
        },
        {
          unit: 0,
          datatype: 0,
          column: "business_status",
          alias: "业务状态",
          compareObj: "待审核",
          satisfy_type: 0,
          varibleType: "values",
          type: 5,
        },
        {
          unit: 0,
          datatype: 0,
          column: "business_status",
          alias: "业务状态",
          compareObj: "待发布审核",
          satisfy_type: 0,
          varibleType: "values",
          type: 5,
        },
      ],
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 17,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "organization_regional_level",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "organization_regional_level",
      col_datatype: 0,
      col_desc: "社会组织所在地-区域层级",
      import_flag: false,
      col_alias: "社会组织所在地-区域层级",
      datatype: 0,
      alias: "社会组织所在地-区域层级",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 18,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "organization_detail_address",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "organization_detail_address",
      col_datatype: 0,
      col_desc: "社会组织所在地-详细地址",
      import_flag: false,
      col_alias: "社会组织所在地-详细地址",
      datatype: 0,
      alias: "社会组织所在地-详细地址",
      inChart: false,
    },
    {
      date: true,
      displayed: 1,
      col_index: 19,
      timeGranularity: 7,
      not_null_flag: 0,
      column: "start_date",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "start_date",
      col_datatype: 6,
      col_desc: "开始时间",
      import_flag: false,
      col_alias: "开始时间",
      datatype: 6,
      alias: "开始时间",
      inChart: false,
    },
    {
      date: true,
      displayed: 1,
      col_index: 20,
      timeGranularity: 7,
      not_null_flag: 0,
      column: "end_date",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "end_date",
      col_datatype: 6,
      col_desc: "截止时间",
      import_flag: false,
      col_alias: "截止时间",
      datatype: 6,
      alias: "截止时间",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 21,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "activity_type",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_type",
      col_datatype: 0,
      col_desc: "服务活动类型",
      import_flag: false,
      col_alias: "服务活动类型",
      datatype: 0,
      alias: "服务活动类型",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 22,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "activity_range",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_range",
      col_datatype: 0,
      col_desc: "服务活动范围",
      import_flag: false,
      col_alias: "服务活动范围",
      datatype: 0,
      alias: "服务活动范围",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 23,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "activity_contacts",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_contacts",
      col_datatype: 0,
      col_desc: "服务活动联系人",
      import_flag: false,
      col_alias: "服务活动联系人",
      datatype: 0,
      alias: "服务活动联系人",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 24,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "activity_contact_number",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_contact_number",
      col_datatype: 0,
      col_desc: "服务活动联系电话",
      import_flag: false,
      col_alias: "服务活动联系电话",
      datatype: 0,
      alias: "服务活动联系电话",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 25,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "activity_picture",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_picture",
      col_datatype: 0,
      col_desc: "宣传图片",
      import_flag: false,
      col_alias: "宣传图片",
      datatype: 0,
      alias: "宣传图片",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 26,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "activity_describe",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_describe",
      col_datatype: 0,
      col_desc: "活动描述",
      import_flag: false,
      col_alias: "活动描述",
      datatype: 0,
      alias: "活动描述",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 27,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "history_activity_describe",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "history_activity_describe",
      col_datatype: 0,
      col_desc: "以往活动描述",
      import_flag: false,
      col_alias: "以往活动描述",
      datatype: 0,
      alias: "以往活动描述",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 28,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "organization_name",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "organization_name",
      col_datatype: 0,
      col_desc: "社会组织名称",
      import_flag: false,
      col_alias: "社会组织名称",
      datatype: 0,
      alias: "社会组织名称",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 29,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "release_status",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "release_status",
      col_datatype: 0,
      col_desc: "发布状态",
      import_flag: false,
      col_alias: "发布状态",
      datatype: 0,
      alias: "发布状态",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 30,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "progress_status",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "progress_status",
      col_datatype: 0,
      col_desc: "进行状态",
      import_flag: false,
      col_alias: "进行状态",
      datatype: 0,
      alias: "进行状态",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 31,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "off_shelf_status",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "off_shelf_status",
      col_datatype: 0,
      col_desc: "下架状态",
      import_flag: false,
      col_alias: "下架状态",
      datatype: 0,
      alias: "下架状态",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 32,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "end_status",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "end_status",
      col_datatype: 0,
      col_desc: "结束状态",
      import_flag: false,
      col_alias: "结束状态",
      datatype: 0,
      alias: "结束状态",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 33,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "activity_contact_country_code",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_contact_country_code",
      col_datatype: 0,
      col_desc: "服务活动联系电话国家代码",
      import_flag: false,
      col_alias: "服务活动联系电话国家代码",
      datatype: 0,
      alias: "服务活动联系电话国家代码",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 34,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "organization_level",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "organization_level",
      col_datatype: 0,
      col_desc: "社会组织层级",
      import_flag: false,
      col_alias: "社会组织层级",
      datatype: 0,
      alias: "社会组织层级",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 35,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "country_code",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "country_code",
      col_datatype: 0,
      col_desc: "国家电话代码",
      import_flag: false,
      col_alias: "国家电话代码",
      datatype: 0,
      alias: "国家电话代码",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 16,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "activity_name",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_name",
      col_datatype: 0,
      col_desc: "活动名称",
      import_flag: false,
      col_alias: "活动名称",
      datatype: 0,
      alias: "活动名称",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 40,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "status",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "status",
      col_datatype: 0,
      import_flag: false,
      datatype: 0,
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 41,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "new_end_status",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "new_end_status",
      col_datatype: 0,
      import_flag: false,
      datatype: 0,
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 42,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "new_end_status1",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "new_end_status1",
      col_datatype: 0,
      import_flag: false,
      datatype: 0,
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 43,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "business_status1",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "business_status1",
      col_datatype: 0,
      import_flag: false,
      datatype: 0,
      inChart: false,
    },
    {
      displayed: 1,
      date: false,
      col_index: 36,
      not_null_flag: 0,
      column: "local_city",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "local_city",
      col_datatype: 0,
      col_desc: "所属地市",
      import_flag: false,
      col_alias: "所属地市",
      datatype: 0,
      alias: "所属地市",
      inChart: false,
    },
    {
      displayed: 1,
      date: false,
      col_index: 37,
      not_null_flag: 0,
      column: "local_district",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "local_district",
      col_datatype: 0,
      col_desc: "所属区县",
      import_flag: false,
      col_alias: "所属区县",
      datatype: 0,
      alias: "所属区县",
      inChart: false,
    },
    {
      displayed: 1,
      date: false,
      col_index: 38,
      not_null_flag: 0,
      column: "local_street",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "local_street",
      col_datatype: 0,
      col_desc: "所属街道",
      import_flag: false,
      col_alias: "所属街道",
      datatype: 0,
      alias: "所属街道",
      inChart: false,
    },
    {
      displayed: 1,
      date: false,
      col_index: 44,
      not_null_flag: 0,
      datatype: 0,
      column: "business_status2",
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "business_status2",
      col_datatype: 0,
      inChart: false,
      import_flag: false,
    },
  ],
  preparedDataColumns: [
    {
      date: false,
      displayed: 1,
      col_index: 1,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "data_id",
      col_datatype: 0,
      col_desc: "主键ID",
      import_flag: false,
      col_alias: "主键ID",
      queryable: 1,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "外键ID",
      col_index: 2,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "parent_id",
      col_datatype: 0,
      col_desc: "外键ID",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "组织ID",
      col_index: 3,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "office_id",
      col_datatype: 0,
      col_desc: "组织ID",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "创建人",
      col_index: 4,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "create_member",
      col_datatype: 0,
      col_desc: "创建人",
      import_flag: false,
    },
    {
      date: true,
      displayed: 1,
      col_alias: "创建时间",
      col_index: 5,
      timeGranularity: 7,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "create_time",
      col_datatype: 6,
      col_desc: "创建时间",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "创建人IP地址",
      col_index: 6,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "create_member_ip_address",
      col_datatype: 0,
      col_desc: "创建人IP地址",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "修改人",
      col_index: 7,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "last_modifier",
      col_datatype: 0,
      col_desc: "修改人",
      import_flag: false,
    },
    {
      date: true,
      displayed: 1,
      col_alias: "修改时间",
      col_index: 8,
      timeGranularity: 7,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "last_modify_time",
      col_datatype: 6,
      col_desc: "修改时间",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "修改人IP地址",
      col_index: 9,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "last_modifier_ip_address",
      col_datatype: 0,
      col_desc: "修改人IP地址",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "流程实例id",
      col_index: 10,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "flow_instance_id",
      col_datatype: 0,
      col_desc: "流程实例id",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "流程名称",
      col_index: 11,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "flow_name",
      col_datatype: 0,
      col_desc: "流程名称",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "流程实例名称",
      col_index: 12,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "flow_instance_name",
      col_datatype: 0,
      col_desc: "流程实例名称",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "处理人",
      col_index: 13,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "handle_usernames",
      col_datatype: 0,
      col_desc: "处理人",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "业务状态",
      col_index: 14,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "business_status",
      col_datatype: 0,
      col_desc: "业务状态",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "流程状态",
      col_index: 15,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "process_status",
      col_datatype: 0,
      col_desc: "流程状态",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "活动名称",
      col_index: 16,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_name",
      col_datatype: 0,
      col_desc: "活动名称",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "社会组织所在地-区域层级",
      col_index: 17,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "organization_regional_level",
      col_datatype: 0,
      col_desc: "社会组织所在地-区域层级",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "社会组织所在地-详细地址",
      col_index: 18,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "organization_detail_address",
      col_datatype: 0,
      col_desc: "社会组织所在地-详细地址",
      import_flag: false,
    },
    {
      date: true,
      displayed: 1,
      col_alias: "开始时间",
      col_index: 19,
      timeGranularity: 7,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "start_date",
      col_datatype: 6,
      col_desc: "开始时间",
      import_flag: false,
    },
    {
      date: true,
      displayed: 1,
      col_alias: "截止时间",
      col_index: 20,
      timeGranularity: 7,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "end_date",
      col_datatype: 6,
      col_desc: "截止时间",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "服务活动类型",
      col_index: 21,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_type",
      col_datatype: 0,
      col_desc: "服务活动类型",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "服务活动范围",
      col_index: 22,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_range",
      col_datatype: 0,
      col_desc: "服务活动范围",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "服务活动联系人",
      col_index: 23,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_contacts",
      col_datatype: 0,
      col_desc: "服务活动联系人",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "服务活动联系电话",
      col_index: 24,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_contact_number",
      col_datatype: 0,
      col_desc: "服务活动联系电话",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "宣传图片",
      col_index: 25,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_picture",
      col_datatype: 0,
      col_desc: "宣传图片",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "活动描述",
      col_index: 26,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_describe",
      col_datatype: 0,
      col_desc: "活动描述",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "以往活动描述",
      col_index: 27,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "history_activity_describe",
      col_datatype: 0,
      col_desc: "以往活动描述",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "社会组织名称",
      col_index: 28,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "organization_name",
      col_datatype: 0,
      col_desc: "社会组织名称",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "发布状态",
      col_index: 29,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "release_status",
      col_datatype: 0,
      col_desc: "发布状态",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "进行状态",
      col_index: 30,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "progress_status",
      col_datatype: 0,
      col_desc: "进行状态",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "下架状态",
      col_index: 31,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "off_shelf_status",
      col_datatype: 0,
      col_desc: "下架状态",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "结束状态",
      col_index: 32,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "end_status",
      col_datatype: 0,
      col_desc: "结束状态",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "服务活动联系电话国家代码",
      col_index: 33,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "activity_contact_country_code",
      col_datatype: 0,
      col_desc: "服务活动联系电话国家代码",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "社会组织层级",
      col_index: 34,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "organization_level",
      col_datatype: 0,
      col_desc: "社会组织层级",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "国家电话代码",
      col_index: 35,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "country_code",
      col_datatype: 0,
      col_desc: "国家电话代码",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "所属地市",
      col_index: 36,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "local_city",
      col_datatype: 0,
      col_desc: "所属地市",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "所属区县",
      col_index: 37,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "local_district",
      col_datatype: 0,
      col_desc: "所属区县",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "所属街道",
      col_index: 38,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "local_street",
      col_datatype: 0,
      col_desc: "所属街道",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 39,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "title",
      col_datatype: 0,
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 40,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "status",
      col_datatype: 0,
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 41,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "new_end_status",
      col_datatype: 0,
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 42,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "new_end_status1",
      col_datatype: 0,
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 43,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "business_status1",
      col_datatype: 0,
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 44,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "6311bb1d-02a3-fa94-bc93-dcddb598e2dc",
      col_name: "business_status2",
      col_datatype: 0,
      import_flag: false,
    },
  ],
  drillDownOption: [],
  filters: [
    {
      unit: 0,
      datatype: 0,
      column: "business_status",
      alias: "业务状态",
      compareObj: "待发起",
      satisfy_type: 0,
      varibleType: "values",
      type: 5,
    },
    {
      unit: 0,
      datatype: 0,
      column: "business_status",
      alias: "业务状态",
      compareObj: "待审核",
      satisfy_type: 0,
      varibleType: "values",
      type: 5,
    },
    {
      unit: 0,
      datatype: 0,
      column: "business_status",
      alias: "业务状态",
      compareObj: "待发布审核",
      satisfy_type: 0,
      varibleType: "values",
      type: 5,
    },
  ],
  version: 1,
  rails: [],
  series: [],
  variable: [],
  layers: [],
  splitKeys: [],
  analysis_engine: 0,
  markers: [],
  fillConfig: {},
  limits: {
    limitN: 5,
    type: 1,
  },
};
export let datasTwo = {
  associations: [],
  transForm: [],
  columns: [
    {
      date: false,
      displayed: 1,
      col_index: 29,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "title",
      multipleComponentFlag: false,
      index: 0,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "title",
      col_datatype: 0,
      import_flag: false,
      datatype: 0,
      inChart: true,
    },
    {
      date: false,
      displayed: 1,
      col_index: 1,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "data_id",
      multipleComponentFlag: false,
      primary_key_flag: 1,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "data_id",
      col_datatype: 0,
      col_desc: "主键ID",
      import_flag: false,
      col_alias: "主键ID",
      queryable: 1,
      datatype: 0,
      alias: "主键ID",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 16,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "office_id",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "office_id",
      col_datatype: 0,
      col_desc: "组织ID",
      import_flag: false,
      col_alias: "组织ID",
      datatype: 0,
      alias: "组织ID",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 10,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "create_member",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "create_member",
      col_datatype: 0,
      col_desc: "创建人",
      import_flag: false,
      col_alias: "创建人",
      datatype: 0,
      alias: "创建人",
      inChart: false,
    },
    {
      date: true,
      displayed: 1,
      col_index: 11,
      timeGranularity: 7,
      not_null_flag: 0,
      column: "create_time",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "create_time",
      col_datatype: 6,
      col_desc: "创建时间",
      import_flag: false,
      col_alias: "创建时间",
      datatype: 6,
      alias: "创建时间",
      inChart: false,
      order: 1,
    },
    {
      date: false,
      displayed: 1,
      col_index: 12,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "create_member_ip_address",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "create_member_ip_address",
      col_datatype: 0,
      col_desc: "创建人IP地址",
      import_flag: false,
      col_alias: "创建人IP地址",
      datatype: 0,
      alias: "创建人IP地址",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 13,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "last_modifier",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "last_modifier",
      col_datatype: 0,
      col_desc: "修改人",
      import_flag: false,
      col_alias: "修改人",
      datatype: 0,
      alias: "修改人",
      inChart: false,
    },
    {
      date: true,
      displayed: 1,
      col_index: 14,
      timeGranularity: 7,
      not_null_flag: 0,
      column: "last_modify_time",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "last_modify_time",
      col_datatype: 6,
      col_desc: "修改时间",
      import_flag: false,
      col_alias: "修改时间",
      datatype: 6,
      alias: "修改时间",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 15,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "last_modifier_ip_address",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "last_modifier_ip_address",
      col_datatype: 0,
      col_desc: "修改人IP地址",
      import_flag: false,
      col_alias: "修改人IP地址",
      datatype: 0,
      alias: "修改人IP地址",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 3,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "project_type",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "project_type",
      col_datatype: 0,
      col_desc: "项目需求类型",
      import_flag: false,
      col_alias: "项目需求类型",
      datatype: 0,
      alias: "项目需求类型",
      inChart: false,
    },
    {
      date: true,
      displayed: 1,
      col_index: 4,
      timeGranularity: 7,
      not_null_flag: 0,
      column: "start_date",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "start_date",
      col_datatype: 6,
      col_desc: "开始时间",
      import_flag: false,
      col_alias: "开始时间",
      datatype: 6,
      alias: "开始时间",
      inChart: false,
    },
    {
      date: true,
      displayed: 1,
      col_index: 5,
      timeGranularity: 7,
      not_null_flag: 0,
      column: "end_date",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "end_date",
      col_datatype: 6,
      col_desc: "截止时间",
      import_flag: false,
      col_alias: "截止时间",
      datatype: 6,
      alias: "截止时间",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 6,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "project_city",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "project_city",
      col_datatype: 0,
      col_desc: "需求所在地-城市",
      import_flag: false,
      col_alias: "需求所在地-城市",
      datatype: 0,
      alias: "需求所在地-城市",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 7,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "project_district",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "project_district",
      col_datatype: 0,
      col_desc: "需求所在地-区县",
      import_flag: false,
      col_alias: "需求所在地-区县",
      datatype: 0,
      alias: "需求所在地-区县",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 8,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "project_street",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "project_street",
      col_datatype: 0,
      col_desc: "需求所在地-街道",
      import_flag: false,
      col_alias: "需求所在地-街道",
      datatype: 0,
      alias: "需求所在地-街道",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 17,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "project_contacts",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "project_contacts",
      col_datatype: 0,
      col_desc: "项目联系人",
      import_flag: false,
      col_alias: "项目联系人",
      datatype: 0,
      alias: "项目联系人",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 19,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "project_describe",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "project_describe",
      col_datatype: 0,
      col_desc: "项目描述",
      import_flag: false,
      col_alias: "项目描述",
      datatype: 0,
      alias: "项目描述",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 18,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "activity_contact_number",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "activity_contact_number",
      col_datatype: 0,
      col_desc: "项目联系人电话",
      import_flag: false,
      col_alias: "项目联系人电话",
      datatype: 0,
      alias: "项目联系人电话",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 2,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "project_name",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "project_name",
      col_datatype: 0,
      col_desc: "项目名称",
      import_flag: false,
      col_alias: "项目名称",
      datatype: 0,
      alias: "项目名称",
      inChart: false,
    },
    {
      displayed: 1,
      date: false,
      col_index: 9,
      not_null_flag: 0,
      column: "activity_contact_country_code",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "activity_contact_country_code",
      col_datatype: 0,
      col_desc: "项目联系人电话国家代码",
      import_flag: false,
      col_alias: "项目联系人电话国家代码",
      datatype: 0,
      alias: "项目联系人电话国家代码",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 21,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "organization_name",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "organization_name",
      col_datatype: 0,
      col_desc: "组织名称",
      import_flag: false,
      col_alias: "组织名称",
      datatype: 0,
      alias: "组织名称",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 22,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "contacts",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "contacts",
      col_datatype: 0,
      col_desc: "联系人",
      import_flag: false,
      col_alias: "联系人",
      datatype: 0,
      alias: "联系人",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 23,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "create_member_enroll",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "create_member_enroll",
      col_datatype: 0,
      col_desc: "创建人",
      import_flag: false,
      col_alias: "创建人",
      datatype: 0,
      alias: "创建人",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 24,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "contact_number",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "contact_number",
      col_datatype: 0,
      col_desc: "联系电话",
      import_flag: false,
      col_alias: "联系电话",
      datatype: 0,
      alias: "联系电话",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 25,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "organization_address",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "organization_address",
      col_datatype: 0,
      col_desc: "联系地址",
      import_flag: false,
      col_alias: "联系地址",
      datatype: 0,
      alias: "联系地址",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 26,
      timeGranularity: 7,
      not_null_flag: 1,
      column: "participate_time",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "participate_time",
      col_datatype: 0,
      col_desc: "参与时间",
      import_flag: false,
      col_alias: "参与时间",
      datatype: 0,
      alias: "参与时间",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 27,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "message",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "message",
      col_datatype: 0,
      col_desc: "合作留言",
      import_flag: false,
      col_alias: "合作留言",
      datatype: 0,
      alias: "合作留言",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 28,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "work_status",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "work_status",
      col_datatype: 0,
      import_flag: false,
      datatype: 0,
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 30,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "状态",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "状态",
      col_datatype: 0,
      import_flag: false,
      datatype: 0,
      inChart: false,
    },
    {
      displayed: 1,
      date: false,
      col_index: 20,
      not_null_flag: 0,
      column: "business_status",
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "business_status",
      col_datatype: 0,
      col_desc: "业务状态",
      import_flag: false,
      col_alias: "业务状态",
      datatype: 0,
      alias: "业务状态",
      inChart: false,
    },
  ],
  preparedDataColumns: [
    {
      date: false,
      displayed: 1,
      col_index: 1,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "data_id",
      col_datatype: 0,
      col_desc: "主键ID",
      import_flag: false,
      col_alias: "主键ID",
      queryable: 1,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "项目名称",
      col_index: 2,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "project_name",
      col_datatype: 0,
      col_desc: "项目名称",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "项目需求类型",
      col_index: 3,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "project_type",
      col_datatype: 0,
      col_desc: "项目需求类型",
      import_flag: false,
    },
    {
      date: true,
      displayed: 1,
      col_alias: "开始时间",
      col_index: 4,
      timeGranularity: 7,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "start_date",
      col_datatype: 6,
      col_desc: "开始时间",
      import_flag: false,
    },
    {
      date: true,
      displayed: 1,
      col_alias: "截止时间",
      col_index: 5,
      timeGranularity: 7,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "end_date",
      col_datatype: 6,
      col_desc: "截止时间",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "需求所在地-城市",
      col_index: 6,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "project_city",
      col_datatype: 0,
      col_desc: "需求所在地-城市",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "需求所在地-区县",
      col_index: 7,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "project_district",
      col_datatype: 0,
      col_desc: "需求所在地-区县",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "需求所在地-街道",
      col_index: 8,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "project_street",
      col_datatype: 0,
      col_desc: "需求所在地-街道",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "项目联系人电话国家代码",
      col_index: 9,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "activity_contact_country_code",
      col_datatype: 0,
      col_desc: "项目联系人电话国家代码",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "创建人",
      col_index: 10,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "create_member",
      col_datatype: 0,
      col_desc: "创建人",
      import_flag: false,
    },
    {
      date: true,
      displayed: 1,
      col_alias: "创建时间",
      col_index: 11,
      timeGranularity: 7,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "create_time",
      col_datatype: 6,
      col_desc: "创建时间",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "创建人IP地址",
      col_index: 12,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "create_member_ip_address",
      col_datatype: 0,
      col_desc: "创建人IP地址",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "修改人",
      col_index: 13,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "last_modifier",
      col_datatype: 0,
      col_desc: "修改人",
      import_flag: false,
    },
    {
      date: true,
      displayed: 1,
      col_alias: "修改时间",
      col_index: 14,
      timeGranularity: 7,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "last_modify_time",
      col_datatype: 6,
      col_desc: "修改时间",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "修改人IP地址",
      col_index: 15,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "last_modifier_ip_address",
      col_datatype: 0,
      col_desc: "修改人IP地址",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "组织ID",
      col_index: 16,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "office_id",
      col_datatype: 0,
      col_desc: "组织ID",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "项目联系人",
      col_index: 17,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "project_contacts",
      col_datatype: 0,
      col_desc: "项目联系人",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "项目联系人电话",
      col_index: 18,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "activity_contact_number",
      col_datatype: 0,
      col_desc: "项目联系人电话",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "项目描述",
      col_index: 19,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "project_describe",
      col_datatype: 0,
      col_desc: "项目描述",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "业务状态",
      col_index: 20,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "business_status",
      col_datatype: 0,
      col_desc: "业务状态",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 21,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "organization_name",
      col_datatype: 0,
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 22,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "contacts",
      col_datatype: 0,
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 23,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "create_member_enroll",
      col_datatype: 0,
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 24,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "contact_number",
      col_datatype: 0,
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 25,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "organization_address",
      col_datatype: 0,
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 26,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "participate_time",
      col_datatype: 0,
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 27,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "message",
      col_datatype: 0,
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 28,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "work_status",
      col_datatype: 0,
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 29,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "title",
      col_datatype: 0,
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 30,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "e04e3ba6-120d-0578-619c-dcf4a840cc2f",
      col_name: "状态",
      col_datatype: 0,
      import_flag: false,
    },
  ],
  drillDownOption: [],
  filters: [],
  version: 1,
  rails: [],
  series: [],
  variable: [],
  layers: [],
  splitKeys: [],
  analysis_engine: 0,
  markers: [],
  fillConfig: {},
  limits: {
    limitN: 5,
    type: 1,
  },
};
export let datasThree = {
  associations: [],
  transForm: [],
  columns: [
    {
      date: false,
      displayed: 1,
      col_index: 29,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "title",
      multipleComponentFlag: false,
      index: 0,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "title",
      col_datatype: 0,
      import_flag: false,
      datatype: 0,
      inChart: true,
    },
    {
      date: false,
      displayed: 1,
      col_index: 1,
      timeGranularity: 0,
      not_null_flag: 1,
      column: "data_id",
      multipleComponentFlag: false,
      primary_key_flag: 1,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "data_id",
      col_datatype: 0,
      col_desc: "主键ID",
      import_flag: false,
      col_alias: "主键ID",
      queryable: 1,
      datatype: 0,
      alias: "主键ID",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 2,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "parent_id",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "parent_id",
      col_datatype: 0,
      col_desc: "外键ID",
      import_flag: false,
      col_alias: "外键ID",
      datatype: 0,
      alias: "外键ID",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 3,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "office_id",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "office_id",
      col_datatype: 0,
      col_desc: "组织ID",
      import_flag: false,
      col_alias: "组织ID",
      datatype: 0,
      alias: "组织ID",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 4,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "create_member",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "create_member",
      col_datatype: 0,
      col_desc: "创建人",
      import_flag: false,
      col_alias: "创建人",
      datatype: 0,
      alias: "创建人",
      inChart: false,
    },
    {
      date: true,
      displayed: 1,
      col_index: 5,
      timeGranularity: 7,
      not_null_flag: 0,
      column: "create_time",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "create_time",
      col_datatype: 6,
      col_desc: "创建时间",
      import_flag: false,
      col_alias: "创建时间",
      datatype: 6,
      alias: "创建时间",
      inChart: false,
      order: 1,
    },
    {
      date: false,
      displayed: 1,
      col_index: 6,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "create_member_ip_address",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "create_member_ip_address",
      col_datatype: 0,
      col_desc: "创建人IP地址",
      import_flag: false,
      col_alias: "创建人IP地址",
      datatype: 0,
      alias: "创建人IP地址",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 7,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "last_modifier",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "last_modifier",
      col_datatype: 0,
      col_desc: "修改人",
      import_flag: false,
      col_alias: "修改人",
      datatype: 0,
      alias: "修改人",
      inChart: false,
    },
    {
      date: true,
      displayed: 1,
      col_index: 8,
      timeGranularity: 7,
      not_null_flag: 0,
      column: "last_modify_time",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "last_modify_time",
      col_datatype: 6,
      col_desc: "修改时间",
      import_flag: false,
      col_alias: "修改时间",
      datatype: 6,
      alias: "修改时间",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 9,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "last_modifier_ip_address",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "last_modifier_ip_address",
      col_datatype: 0,
      col_desc: "修改人IP地址",
      import_flag: false,
      col_alias: "修改人IP地址",
      datatype: 0,
      alias: "修改人IP地址",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 10,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "flow_instance_id",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "flow_instance_id",
      col_datatype: 0,
      col_desc: "流程实例id",
      import_flag: false,
      col_alias: "流程实例id",
      datatype: 0,
      alias: "流程实例id",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 11,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "flow_name",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "flow_name",
      col_datatype: 0,
      col_desc: "流程名称",
      import_flag: false,
      col_alias: "流程名称",
      datatype: 0,
      alias: "流程名称",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 12,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "flow_instance_name",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "flow_instance_name",
      col_datatype: 0,
      col_desc: "流程实例名称",
      import_flag: false,
      col_alias: "流程实例名称",
      datatype: 0,
      alias: "流程实例名称",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 13,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "handle_usernames",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "handle_usernames",
      col_datatype: 0,
      col_desc: "处理人",
      import_flag: false,
      col_alias: "处理人",
      datatype: 0,
      alias: "处理人",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 14,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "business_status",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "business_status",
      col_datatype: 0,
      col_desc: "业务状态",
      import_flag: false,
      col_alias: "业务状态",
      datatype: 0,
      alias: "业务状态",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 15,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "process_status",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "process_status",
      col_datatype: 0,
      col_desc: "流程状态",
      import_flag: false,
      col_alias: "流程状态",
      datatype: 0,
      alias: "流程状态",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 17,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "demand_type",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "demand_type",
      col_datatype: 0,
      col_desc: "需求类型",
      import_flag: false,
      col_alias: "需求类型",
      datatype: 0,
      alias: "需求类型",
      inChart: false,
    },
    {
      date: true,
      displayed: 1,
      col_index: 18,
      timeGranularity: 4,
      not_null_flag: 0,
      column: "start_date",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "start_date",
      col_datatype: 6,
      col_desc: "开始时间",
      import_flag: false,
      col_alias: "开始时间",
      datatype: 6,
      alias: "开始时间",
      inChart: false,
    },
    {
      date: true,
      displayed: 1,
      col_index: 19,
      timeGranularity: 4,
      not_null_flag: 0,
      column: "end_date",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "end_date",
      col_datatype: 6,
      col_desc: "截止时间",
      import_flag: false,
      col_alias: "截止时间",
      datatype: 6,
      alias: "截止时间",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 20,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "demand_city",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "demand_city",
      col_datatype: 0,
      col_desc: "需求所在地-城市",
      import_flag: false,
      col_alias: "需求所在地-城市",
      datatype: 0,
      alias: "需求所在地-城市",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 21,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "demand_detail_address",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "demand_detail_address",
      col_datatype: 0,
      col_desc: "需求所在地-详细地址",
      import_flag: false,
      col_alias: "需求所在地-详细地址",
      datatype: 0,
      alias: "需求所在地-详细地址",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 22,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "demand_describe",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "demand_describe",
      col_datatype: 0,
      col_desc: "需求描述",
      import_flag: false,
      col_alias: "需求描述",
      datatype: 0,
      alias: "需求描述",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 23,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "organization_name",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "organization_name",
      col_datatype: 0,
      col_desc: "工会名称",
      import_flag: false,
      col_alias: "工会名称",
      datatype: 0,
      alias: "工会名称",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 24,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "organization_level",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "organization_level",
      col_datatype: 0,
      col_desc: "工会层级",
      import_flag: false,
      col_alias: "工会层级",
      datatype: 0,
      alias: "工会层级",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 25,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "organization_regional_level",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "organization_regional_level",
      col_datatype: 0,
      col_desc: "工会所在地-区域层级",
      import_flag: false,
      col_alias: "工会所在地-区域层级",
      datatype: 0,
      alias: "工会所在地-区域层级",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 26,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "organization_detail_address",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "organization_detail_address",
      col_datatype: 0,
      col_desc: "工会所在地-详细地址",
      import_flag: false,
      col_alias: "工会所在地-详细地址",
      datatype: 0,
      alias: "工会所在地-详细地址",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 27,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "demand_district",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "demand_district",
      col_datatype: 0,
      col_desc: "需求所在地-区县",
      import_flag: false,
      col_alias: "需求所在地-区县",
      datatype: 0,
      alias: "需求所在地-区县",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 28,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "demand_street",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "demand_street",
      col_datatype: 0,
      col_desc: "需求所在地-街道",
      import_flag: false,
      col_alias: "需求所在地-街道",
      datatype: 0,
      alias: "需求所在地-街道",
      inChart: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 16,
      timeGranularity: 0,
      not_null_flag: 0,
      column: "demand_name",
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "demand_name",
      col_datatype: 0,
      col_desc: "需求名称",
      import_flag: false,
      col_alias: "需求名称",
      datatype: 0,
      alias: "需求名称",
      inChart: false,
    },
  ],
  preparedDataColumns: [
    {
      date: false,
      displayed: 1,
      col_index: 1,
      timeGranularity: 0,
      not_null_flag: 1,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "data_id",
      col_datatype: 0,
      col_desc: "主键ID",
      import_flag: false,
      col_alias: "主键ID",
      queryable: 1,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "外键ID",
      col_index: 2,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "parent_id",
      col_datatype: 0,
      col_desc: "外键ID",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "组织ID",
      col_index: 3,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "office_id",
      col_datatype: 0,
      col_desc: "组织ID",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "创建人",
      col_index: 4,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "create_member",
      col_datatype: 0,
      col_desc: "创建人",
      import_flag: false,
    },
    {
      date: true,
      displayed: 1,
      col_alias: "创建时间",
      col_index: 5,
      timeGranularity: 7,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "create_time",
      col_datatype: 6,
      col_desc: "创建时间",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "创建人IP地址",
      col_index: 6,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "create_member_ip_address",
      col_datatype: 0,
      col_desc: "创建人IP地址",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "修改人",
      col_index: 7,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "last_modifier",
      col_datatype: 0,
      col_desc: "修改人",
      import_flag: false,
    },
    {
      date: true,
      displayed: 1,
      col_alias: "修改时间",
      col_index: 8,
      timeGranularity: 7,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "last_modify_time",
      col_datatype: 6,
      col_desc: "修改时间",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "修改人IP地址",
      col_index: 9,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "last_modifier_ip_address",
      col_datatype: 0,
      col_desc: "修改人IP地址",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "流程实例id",
      col_index: 10,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "flow_instance_id",
      col_datatype: 0,
      col_desc: "流程实例id",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "流程名称",
      col_index: 11,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "flow_name",
      col_datatype: 0,
      col_desc: "流程名称",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "流程实例名称",
      col_index: 12,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "flow_instance_name",
      col_datatype: 0,
      col_desc: "流程实例名称",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "处理人",
      col_index: 13,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "handle_usernames",
      col_datatype: 0,
      col_desc: "处理人",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "业务状态",
      col_index: 14,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "business_status",
      col_datatype: 0,
      col_desc: "业务状态",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "流程状态",
      col_index: 15,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "process_status",
      col_datatype: 0,
      col_desc: "流程状态",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "需求名称",
      col_index: 16,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "demand_name",
      col_datatype: 0,
      col_desc: "需求名称",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "需求类型",
      col_index: 17,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "demand_type",
      col_datatype: 0,
      col_desc: "需求类型",
      import_flag: false,
    },
    {
      date: true,
      displayed: 1,
      col_alias: "开始时间",
      col_index: 18,
      timeGranularity: 7,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "start_date",
      col_datatype: 6,
      col_desc: "开始时间",
      import_flag: false,
    },
    {
      date: true,
      displayed: 1,
      col_alias: "截止时间",
      col_index: 19,
      timeGranularity: 7,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "end_date",
      col_datatype: 6,
      col_desc: "截止时间",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "需求所在地-城市",
      col_index: 20,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "demand_city",
      col_datatype: 0,
      col_desc: "需求所在地-城市",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "需求所在地-详细地址",
      col_index: 21,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "demand_detail_address",
      col_datatype: 0,
      col_desc: "需求所在地-详细地址",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "需求描述",
      col_index: 22,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "demand_describe",
      col_datatype: 0,
      col_desc: "需求描述",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "工会名称",
      col_index: 23,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "organization_name",
      col_datatype: 0,
      col_desc: "工会名称",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "工会层级",
      col_index: 24,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "organization_level",
      col_datatype: 0,
      col_desc: "工会层级",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "工会所在地-区域层级",
      col_index: 25,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "organization_regional_level",
      col_datatype: 0,
      col_desc: "工会所在地-区域层级",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "工会所在地-详细地址",
      col_index: 26,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "organization_detail_address",
      col_datatype: 0,
      col_desc: "工会所在地-详细地址",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "需求所在地-区县",
      col_index: 27,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "demand_district",
      col_datatype: 0,
      col_desc: "需求所在地-区县",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_alias: "需求所在地-街道",
      col_index: 28,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "demand_street",
      col_datatype: 0,
      col_desc: "需求所在地-街道",
      import_flag: false,
    },
    {
      date: false,
      displayed: 1,
      col_index: 29,
      timeGranularity: 0,
      not_null_flag: 0,
      multipleComponentFlag: false,
      asset_id: "e7f98a6d-8611-b2eb-2839-f885cec11a17",
      col_name: "title",
      col_datatype: 0,
      import_flag: false,
    },
  ],
  drillDownOption: [],
  filters: [],
  version: 1,
  rails: [],
  series: [],
  variable: [],
  layers: [],
  splitKeys: [],
  analysis_engine: 0,
  markers: [],
  fillConfig: {},
  limits: {
    limitN: 5,
    type: 1,
  },
};
export default {
  datasOne,
  datasTwo,
  datasThree,
};
